[project]
name = "echo-robot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ruff>=0.12.5",
]

[tool.uv.workspace]
members = [
    "echo-robot",
]
